apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: was-hpa
  namespace: nsX
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websphere-liberty-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
