apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websphere-liberty-ingress
  namespace: nsX
spec:
  rules:
    - host: websphere-liberty-app-nsX.at-pot-b3f0fc3fa0c3a208d8bb1467220af510-0000.eu-de.containers.appdomain.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websphere-liberty-service1
                port: 
                  number: 9080
